const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chão: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{player: 0},
	{Teclado: 0},
	{plataforma_1: 0},
	{plataforma_2: 0},
	{plataforma_3: 0},
	{Senóide: 0},
	{plataforma_4: 0},
	{bola: 0},
	{bandeira_fase1: 0},
	{imagem_1: 0},
	{imagem_2: 0},
	{imagem_3: 0},
	{imagem_4: 0},
	{morte: 0},
	{Áudio: 0},
	{Fixar: 0},
	{grama_1: 0},
	{grama_2: 0},
	{bandeira_fase2: 0},
	{p: 0},
	{preto: 0}
];

self.InstanceType = {
	chão: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	plataforma_1: class extends self.ISpriteInstance {},
	plataforma_2: class extends self.ISpriteInstance {},
	plataforma_3: class extends self.ISpriteInstance {},
	plataforma_4: class extends self.ISpriteInstance {},
	bola: class extends self.ISpriteInstance {},
	bandeira_fase1: class extends self.ISpriteInstance {},
	imagem_1: class extends self.ISpriteInstance {},
	imagem_2: class extends self.ISpriteInstance {},
	imagem_3: class extends self.ISpriteInstance {},
	imagem_4: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	grama_1: class extends self.ISpriteInstance {},
	grama_2: class extends self.ISpriteInstance {},
	bandeira_fase2: class extends self.ISpriteInstance {},
	p: class extends self.ISpriteInstance {},
	preto: class extends self.ISpriteInstance {}
}